game:
- name: 넷마블
  corp_code: 00904672
  stock_code: '251270'
  kpmg: true
- name: 엔씨소프트
  corp_code: '00261443'
  stock_code: '036570'
  kpmg: true
- name: 크래프톤
  corp_code: 00760971
  stock_code: '259960'
  kpmg: true
- name: 펄어비스
  corp_code: '01152470'
  stock_code: '263750'
  kpmg: true
- name: 카카오게임즈
  corp_code: 01137383
  stock_code: '293490'
  kpmg: true
- name: 웹젠
  corp_code: '00405320'
  stock_code: 069080
  kpmg: true
- name: 넵튠
  corp_code: 01067808
  stock_code: '217270'
  kpmg: true
- name: 위메이드플레이
  corp_code: 00815767
  stock_code: '123420'
  kpmg: true
- name: 스마일게이트
  corp_code: 00868194
  stock_code: ''
  kpmg: true
- name: 스마일게이트알피지
  corp_code: 00961756
  stock_code: ''
  kpmg: true
- name: 넥슨게임즈
  corp_code: 01096341
  stock_code: '225570'
- name: 컴투스
  corp_code: 00476498
  stock_code: 078340
- name: 위메이드
  corp_code: 00444329
  stock_code: '112040'
- name: 네오위즈
  corp_code: 00628860
  stock_code: 095660
- name: 더블유게임즈
  corp_code: '01010110'
  stock_code: '192080'
- name: 시프트업
  corp_code: 01384787
  stock_code: '462870'
- name: 데브시스터즈
  corp_code: 01008762
  stock_code: '194480'
entertainment:
- name: 에스엠엔터테인먼트
  corp_code: 00260930
  stock_code: '041510'
  kpmg: true
- name: 제이와이피엔터테인먼트
  corp_code: 00258689
  stock_code: 035900
  kpmg: true
- name: 디어유
  corp_code: '01456011'
  stock_code: '376300'
  kpmg: true
- name: 드림어스컴퍼니
  corp_code: '00364467'
  stock_code: '060570'
  kpmg: true
- name: 하이브
  corp_code: '01204056'
  stock_code: '352820'
- name: 와이지엔터테인먼트
  corp_code: 00613318
  stock_code: '122870'
- name: 큐브엔터
  corp_code: 00985686
  stock_code: '182360'
media:
- name: 제일기획
  corp_code: 00148276
  stock_code: '030000'
  kpmg: true
- name: 이노션
  corp_code: '00565154'
  stock_code: '214320'
  kpmg: true
- name: 오리콤
  corp_code: '00141671'
  stock_code: '010470'
  kpmg: true
- name: 인크로스
  corp_code: 00819073
  stock_code: '216050'
  kpmg: true
- name: 엘지헬로비전
  corp_code: '00222532'
  stock_code: '037560'
  kpmg: true
- name: 딜라이브
  corp_code: 00364935
  stock_code: ''
  kpmg: true
- name: 씨제이이엔엠스튜디오스
  corp_code: '01674750'
  stock_code: ''
  kpmg: true
- name: 씨제이포디플렉스
  corp_code: 00866691
  stock_code: ''
  kpmg: true
- name: 위지윅스튜디오
  corp_code: '01276327'
  stock_code: '299900'
  kpmg: true
- name: 씨제이이엔엠
  corp_code: '00265324'
  stock_code: '035760'
- name: 스튜디오드래곤
  corp_code: 01168684
  stock_code: '253450'
- name: 콘텐트리중앙
  corp_code: '00203315'
  stock_code: '036420'
- name: 에스비에스
  corp_code: '00130772'
  stock_code: '034120'
- name: 나스미디어
  corp_code: 00486097
  stock_code: 089600
telecom:
- name: 에스케이브로드밴드
  corp_code: 00243988
  stock_code: '033630'
  kpmg: true
- name: 에스케이텔레콤
  corp_code: 00159023
  stock_code: '017670'
- name: 케이티
  corp_code: 00190321
  stock_code: '030200'
- name: 엘지유플러스
  corp_code: '00231363'
  stock_code: '032640'
it:
- name: 네이버
  corp_code: 00266961
  stock_code: '035420'
  kpmg: true
- name: 카카오
  corp_code: 00258801
  stock_code: '035720'
  kpmg: true
- name: 카카오엔터프라이즈
  corp_code: '01411434'
  stock_code: ''
  kpmg: true
- name: 카페24
  corp_code: 00260879
  stock_code: '042000'
  kpmg: true
- name: 두나무
  corp_code: '01310241'
  stock_code: ''
  kpmg: true
- name: 당근마켓
  corp_code: 01547845
  stock_code: ''
  kpmg: true
- name: 야놀자
  corp_code: 00907864
  stock_code: ''
  kpmg: true
- name: 다우기술
  corp_code: 00176914
  stock_code: 023590
  kpmg: true
- name: 다우데이타
  corp_code: 00238782
  stock_code: 032190
  kpmg: true
- name: 신한디에스
  corp_code: '00664710'
  stock_code: ''
  kpmg: true
- name: 에스케이쉴더스
  corp_code: 00414975
  stock_code: ''
  kpmg: true
- name: 메가존클라우드
  corp_code: '01353635'
  stock_code: ''
  kpmg: true
- name: 베스핀글로벌
  corp_code: '01377574'
  stock_code: ''
  kpmg: true
- name: 슈프리마
  corp_code: '01124653'
  stock_code: '236200'
  kpmg: true
- name: 이스트소프트
  corp_code: '00273420'
  stock_code: '047560'
  kpmg: true
- name: 삼성에스디에스
  corp_code: 00126186
  stock_code: 018260
- name: 엘지씨엔에스
  corp_code: 00139834
  stock_code: '064400'
- name: 더존비즈온
  corp_code: 00172291
  stock_code: '012510'
- name: 엔에이치엔
  corp_code: 00983271
  stock_code: '181710'
- name: 안랩
  corp_code: 00298270
  stock_code: 053800
- name: 우아한형제들
  corp_code: '01063273'
  stock_code: ''
- name: 비바리퍼블리카
  corp_code: 01212921
  stock_code: ''
- name: 쿠팡
  corp_code: 01019166
  stock_code: ''
- name: 무신사
  corp_code: '01137727'
  stock_code: ''
- name: 컬리
  corp_code: 01153956
  stock_code: ''
